export default {
  extends: ['stylelint-config-standard', 'stylelint-config-styled-components', 'stylelint-prettier/recommended'],
  customSyntax: '@stylelint/postcss-css-in-js',
  plugins: ['stylelint-prettier'],
  rules: {
    'prettier/prettier': true,
    'at-rule-no-unknown': null,
    'value-keyword-case': null,
    'function-no-unknown': null,
    'declaration-empty-line-before': 'never',
    'selector-class-pattern': null,
    'keyframes-name-pattern': null,
    'declaration-block-no-redundant-longhand-properties': true,
    'shorthand-property-no-redundant-values': true,
    'selector-not-notation': 'simple',
    'alpha-value-notation': 'number',
    'color-function-notation': 'legacy',
    'no-descending-specificity': null,
    'value-no-vendor-prefix': [true, { ignoreValues: ['box'] }],
    'property-no-vendor-prefix': [true, { ignoreProperties: ['box-orient'] }],
    'function-url-quotes': 'always',
    'selector-attribute-quotes': 'always',
  },
}
