export const DESSERT = [
  {
    metaSeo: {
      title: 'Чизкейк',
      description:
        'Чизкейк — это изысканный десерт, покоривший миллионы сладкоежек по всему миру. Его основа — нежная сливочная начинка на песочной корже, которая буквально тает во рту. В отличие от привычных пирожных, чизкейк не требует выпечки (хотя есть и запечённые варианты), а его вкус балансирует между лёгкой кислинкой и сладкой сливочностью.',
      keywords: ['чизкейк', 'пирожное', 'десерт'],
      'og:title': 'Чизкейк',
      'og:description':
        'Чизкейк — это изысканный десерт, покоривший миллионы сладкоежек по всему миру. Его основа — нежная сливочная начинка на песочной корже, которая буквально тает во рту. В отличие от привычных пирожных, чизкейк не требует выпечки (хотя есть и запечённые варианты), а его вкус балансирует между лёгкой кислинкой и сладкой сливочностью.',
      'og:url': 'https://povreshka.ru/recipe/chizkeik',
      'og:image': '/static/recipes/dessert/chizkeik.jpeg',
      twitterTitle: 'Чизкейк',
      twitterDescription:
        'Чизкейк — это изысканный десерт, покоривший миллионы сладкоежек по всему миру. Его основа — нежная сливочная начинка на песочной корже, которая буквально тает во рту. В отличие от привычных пирожных, чизкейк не требует выпечки (хотя есть и запечённые варианты), а его вкус балансирует между лёгкой кислинкой и сладкой сливочностью.',
      twitterImage: '/static/recipes/dessert/chizkeik.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/chizkeik',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/chizkeik',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['чизкейк', 'пирожное', 'десерт'],
    categories: [{ name: 'dessert' }],
    key: 'chizkeik',
    name: 'chizkeik',
    img: '/static/recipes/dessert/chizkeik.jpeg',
    title: 'Чизкейк',
    description:
      'Чизкейк — это изысканный десерт, покоривший миллионы сладкоежек по всему миру. Его основа — нежная сливочная начинка на песочной корже, которая буквально тает во рту. В отличие от привычных пирожных, чизкейк не требует выпечки (хотя есть и запечённые варианты), а его вкус балансирует между лёгкой кислинкой и сладкой сливочностью.',
    calories: 353.28,
    preparation: 60,
    time: 75,
    level: 2,
    rating: 5,
    portions: 12,
    used: [9.46, 22.6, 27.5],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Подготовьте форму для выпекания диаметром 24 см: застелите дно пергаментом и плотно оберните форму фольгой — это важно для водяной бани, чтобы чизкейк получился воздушным и нежным.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Измельчите печенье (например, "Юбилейное") до мелкой крошки с помощью блендера. Постепенно добавляйте молоко, добиваясь липкой текстуры. Выложите массу в форму, утрамбуйте стаканом или руками и поставьте в холодильник.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Для нежной начинки соедините в глубокой миске творожный сыр и рикотту. Вводите по одному яйцу, аккуратно размешивая венчиком или силиконовой лопаткой, чтобы сохранить воздушность.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Охлажденные сливки жирностью 33% взбивайте сначала на низкой скорости 2–3 минуты, затем переключитесь на высокую и продолжайте до устойчивой пышной массы — около 5 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Аккуратно соедините взбитые сливки с сырной основой, перемешивая круговыми движениями. Добавьте сахар небольшими порциями, добиваясь гладкой, однородной текстуры.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Вылейте получившуюся сырную смесь в охлажденную форму. Постучите формой о стол, чтобы удалить лишний воздух. Поместите форму в глубокий противень, налейте кипяток — водяная баня обеспечит равномерную выпечку.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разогрейте духовку до 160 °C и запекайте чизкейк 1 час 15 минут. Первые 30–40 минут не открывайте дверцу, чтобы сохранить стабильную температуру и влажность.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Проверить готовность просто: слегка потрясите форму — если середина чизкейка подрагивает, как желе, он готов. Не пересушите десерт, чтобы сохранить его кремовую текстуру.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Выключите духовку и оставьте чизкейк остывать внутри примерно на 40 минут. Затем дайте ему постоять при комнатной температуре и уберите на ночь в холодильник для стабилизации.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Перед подачей аккуратно извлеките чизкейк из формы, снимите пергамент и, при желании, украсьте его свежими ягодами, фруктами или мятой. Наслаждайтесь нежным домашним чизкейком!',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
      description:
        'Нежная панна котта с хрустящей карамельной корочкой и кисло-сладким малиновым соусом. Секреты идеальной текстуры без комочков, 3 варианта подачи и советы по выбору сливок. Охлаждается 4 часа.',
      keywords: [
        'панна котта',
        'итальянский десерт',
        'десерт со сливками',
        'легкий десерт',
        'десерт без выпечки',
        'малиновый соус',
        'десерт с желатином',
        'холодный десерт',
        'десерт за 15 минут',
        'ресторанный десерт',
        'ванильная панна котта',
        'десерт в стаканчиках',
        'праздничный десерт',
        'низкокалорийный вариант',
        'веганская панна котта',
      ],
      'og:title': 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
      'og:description':
        'Нежная панна котта с хрустящей карамельной корочкой и кисло-сладким малиновым соусом. Секреты идеальной текстуры без комочков.',
      'og:url': 'https://povreshka.ru/recipe/panna-cotta',
      'og:image': '/static/recipes/dessert/panna-cotta.jpeg',
      twitterTitle: 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
      twitterDescription: 'Нежная панна котта с бархатистой текстурой — готовится за 15 минут!',
      twitterImage: '/static/recipes/dessert/panna-cotta.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/panna-cotta',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/panna-cotta',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'панна котта',
      'итальянский десерт',
      'десерт без выпечки',
      'холодный десерт',
      'десерт со сливками',
    ],
    categories: [{ name: 'dessert' }],
    key: 'panna-cotta',
    name: 'panna-cotta',
    img: '/static/recipes/dessert/panna-cotta.jpeg',
    title: 'Панна котта с малиной',
    description:
      'Классический итальянский десерт с бархатистой текстурой, который тает во рту. Наш вариант сочетает ванильные нотки сливочной основы с ярким контрастом малинового соуса. Секрет — точная температура нагрева сливок и правильное растворение желатина.',
    calories: 280,
    preparation: 15,
    time: 255,
    level: 1,
    rating: 4.8,
    portions: 4,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'В сотейнике смешайте сливки, ванильный стручок и сахар. Нагревайте на медленном огне до 80°C, не допуская кипения. Снимите с огня, удалите ваниль.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Замочите желатин в холодной воде на 5 минут. Отожмите и растворите в горячих сливках, тщательно размешивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Разлейте смесь по формочкам, охладите до комнатной температуры. Уберите в холодильник на 4 часа.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Для соуса протрите малину через сито, смешайте с сахарной пудрой. Подавайте панна котту, поливая соусом.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Трюфельные конфеты с фундуком — шоколадный десерт за 30 минут',
      description:
        'Домашние трюфели с хрустящим фундуком внутри: простой рецепт с фото. 3 вида шоколада, секреты темперирования и 5 вариантов украшения. Без выпечки, хранятся 2 недели.',
      keywords: [
        'трюфельные конфеты',
        'шоколадные конфеты',
        'домашний шоколад',
        'десерт без выпечки',
        'быстрый десерт',
        'десерт с фундуком',
        'шоколадный трюфель',
        'подарок своими руками',
        'романтический десерт',
        'десерт за 30 минут',
        'темный шоколад',
        'праздничные конфеты',
        'веганские трюфели',
        'десерт в подарок',
        'шоколадный десерт',
      ],
      'og:title': 'Трюфельные конфеты с фундуком — шоколадный десерт за 30 минут',
      'og:description':
        'Домашние трюфели с хрустящим фундуком: простой рецепт с фото. 3 вида шоколада и 5 вариантов украшения.',
      'og:url': 'https://povreshka.ru/recipe/chocolate-truffles',
      'og:image': '/static/recipes/dessert/chocolate-truffles.jpeg',
      twitterTitle: 'Трюфельные конфеты с фундуком — шоколадный десерт за 30 минут',
      twitterDescription: 'Шоколадные трюфели с сюрпризом внутри — готовятся за 30 минут!',
      twitterImage: '/static/recipes/dessert/chocolate-truffles.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/chocolate-truffles',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/chocolate-truffles',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'трюфельные конфеты',
      'шоколадный десерт',
      'домашние конфеты',
      'десерт без выпечки',
      'десерт с фундуком',
    ],
    categories: [{ name: 'dessert' }],
    key: 'chocolate-truffles',
    name: 'chocolate-truffles',
    img: '/static/recipes/dessert/chocolate-truffles.jpeg',
    title: 'Трюфельные конфеты с фундуком',
    description:
      'Аристократичный десерт французской кухни в домашнем исполнении. Нежная шоколадная паста с цельным фундуком внутри, покрытая хрустящей шоколадной глазурью. Особенность рецепта — сочетание трех видов шоколада (горький, молочный и белый) для сложного вкусового профиля.',
    calories: 150,
    preparation: 30,
    time: 60,
    level: 2,
    rating: 4.9,
    portions: 20,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'На водяной бане растопите горький шоколад со сливками, постоянно помешивая. Добавьте сливочное масло, снимите с огня.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Охладите массу до комнатной температуры, затем уберите в холодильник на 20 минут до загустения.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Сформируйте шарики с цельным фундуком внутри. Обваляйте в какао или растопленном шоколаде.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Дайте конфетам застыть на пергаменте 30 минут. Храните в холодильнике в герметичной таре.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Меренговый рулет с лимонным курдом — воздушный десерт',
      description:
        'Нежный меренговый рулет с кисло-сладкой лимонной начинкой: пошаговый рецепт с фото. Секреты устойчивых пиков, правильная температура духовки и варианты украшения. Выпекается 1 час.',
      keywords: [
        'меренговый рулет',
        'десерт с меренгой',
        'лимонный курд',
        'воздушный десерт',
        'десерт с лимоном',
        'рулет без муки',
        'легкий десерт',
        'десерт для гостей',
        'праздничный десерт',
        'меренга с начинкой',
        'десерт за 1 час',
        'безглютеновый десерт',
        'десерт с ягодами',
        'летний десерт',
        'сладкий рулет',
      ],
      'og:title': 'Меренговый рулет с лимонным курдом — воздушный десерт',
      'og:description':
        'Нежный меренговый рулет с кисло-сладкой лимонной начинкой: пошаговый рецепт с фото. Секреты устойчивых пиков.',
      'og:url': 'https://povreshka.ru/recipe/meringue-roll-s-lemon-curd',
      'og:image': '/static/recipes/dessert/meringue-roll-s-lemon-curd.jpeg',
      twitterTitle: 'Меренговый рулет с лимонным курдом — воздушный десерт',
      twitterDescription: 'Воздушная меренга с лимонным курдом — тает во рту!',
      twitterImage: '/static/recipes/dessert/meringue-roll-s-lemon-curd.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/meringue-roll-s-lemon-curd',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/meringue-roll-s-lemon-curd',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['меренговый рулет', 'десерт с меренгой', 'лимонный курд', 'воздушный десерт', 'десерт без муки'],
    categories: [{ name: 'dessert' }],
    key: 'meringue-roll-s-lemon-curd',
    name: 'meringue-roll-s-lemon-curd',
    img: '/static/recipes/dessert/meringue-roll-s-lemon-curd.jpeg',
    title: 'Меренговый рулет с лимоном',
    description:
      'Контрастный десерт, сочетающий хрустящую снаружи и мягкую внутри меренгу с бархатистым лимонным курдом. Особенность рецепта — французская меренга с идеально стабильными пиками и курд, приготовленный на водяной бане для шелковистой текстуры. Подается охлажденным с свежими ягодами.',
    calories: 210,
    preparation: 30,
    time: 90,
    level: 3,
    rating: 4.7,
    portions: 8,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Взбейте белки с сахаром до устойчивых пиков. Добавьте кукурузный крахмал и лимонный сок, аккуратно перемешайте.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Выложите меренгу на противень с пергаментом, формируя прямоугольник. Выпекайте при 120°C 1 час.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Для курда смешайте все ингредиенты и варите на водяной бане до загустения. Охладите.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Сверните остывшую меренгу с начинкой в рулет. Украсьте сахарной пудрой.',
        ingredients: [],
      },
    ],
  },

  {
    metaSeo: {
      title: 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
      description:
        'Классический американский клубничный пай с рассыпчатой крошкой: пошаговый рецепт с фото. Секреты сочной начинки, идеального теста и подачи со взбитыми сливками. Выпекается 30 минут.',
      keywords: [
        'клубничный пай',
        'американский десерт',
        'десерт с клубникой',
        'песочный десерт',
        'фруктовый пирог',
        'десерт с крошкой',
        'летний десерт',
        'десерт за 45 минут',
        'домашний пирог',
        'клубника в десерте',
        'рассыпчатый десерт',
        'десерт со сливками',
        'праздничный пай',
        'сладкая выпечка',
        'десерт к чаю',
      ],
      'og:title': 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
      'og:description':
        'Классический американский клубничный пай с рассыпчатой крошкой: секреты сочной начинки и идеального теста.',
      'og:url': 'https://povreshka.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
      'og:image': '/static/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.jpeg',
      twitterTitle: 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
      twitterDescription: 'Ароматный клубничный пай с хрустящей крошкой — вкус лета!',
      twitterImage: '/static/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'клубничный пай',
      'американский десерт',
      'десерт с клубникой',
      'фруктовый пирог',
      'десерт с крошкой',
    ],
    categories: [{ name: 'dessert' }],
    key: 'klubnichnyy-pai-s-pesochnoy-kroschkoy',
    name: 'klubnichnyy-pai-s-pesochnoy-kroschkoy',
    img: '/static/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.jpeg',
    title: 'Клубничный пай с крошкой',
    description:
      'Традиционный американский десерт с сочной клубничной начинкой и хрустящей песочной крошкой. Особенность рецепта — сочетание свежей и слегка припущенной клубники для идеального баланса текстуры, а также добавление миндальной муки в крошку для особой рассыпчатости. Подается теплым с шариком ванильного мороженого.',
    calories: 320,
    preparation: 15,
    time: 45,
    level: 2,
    rating: 4.8,
    portions: 6,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Для крошки смешайте муку, холодное масло и сахар руками до состояния крупных крошек. Добавьте миндальную муку.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Клубнику смешайте с сахаром и крахмалом, половину пюрируйте блендером.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Выложите начинку в форму, посыпьте крошкой. Выпекайте при 180°C 30 минут до золотистого цвета.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
      description:
        'Аутентичный крем-брюле как в парижских ресторанах: нежный ванильный крем под карамельной корочкой. Секреты идеальной текстуры, техника карамелизации и выбор ванили. Готовится за 50 минут + охлаждение.',
      keywords: [
        'крем-брюле',
        'французский десерт',
        'десерт с карамелью',
        'ванильный десерт',
        'десерт в рамекинах',
        'классический десерт',
        'ресторанный десерт',
        'десерт за 50 минут',
        'десерт с хрустящей корочкой',
        'яичный десерт',
        'праздничный десерт',
        'десерт для гостей',
        'легкий десерт',
        'десерт с сахарной корочкой',
        'традиционный десерт',
      ],
      'og:title': 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
      'og:description':
        'Аутентичный крем-брюле: нежный ванильный крем под карамельной корочкой. Секреты идеальной текстуры.',
      'og:url': 'https://povreshka.ru/recipe/krem-bryule-s-vanilyu',
      'og:image': '/static/recipes/dessert/krem-bryule-s-vanilyu.jpeg',
      twitterTitle: 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
      twitterDescription: 'Французский крем-брюле с хрустящей карамелью — просто и изысканно!',
      twitterImage: '/static/recipes/dessert/krem-bryule-s-vanilyu.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/krem-bryule-s-vanilyu',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/krem-bryule-s-vanilyu',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'крем-брюле',
      'французский десерт',
      'десерт с карамелью',
      'ванильный десерт',
      'десерт в рамекинах',
    ],
    categories: [{ name: 'dessert' }],
    key: 'krem-bryule-s-vanilyu',
    name: 'krem-bryule-s-vanilyu',
    img: '/static/recipes/dessert/krem-bryule-s-vanilyu.jpeg',
    title: 'Крем-брюле ванильное',
    description:
      'Знаковый французский десерт с историей в 300 лет — нежный заварной крем на основе ванильных стручков таитянского сорта, покрытый стекловидным слоем карамели. Особенность приготовления — точный температурный контроль на водяной бане и использование тростникового сахара для карамелизации.',
    calories: 380,
    preparation: 20,
    time: 290,
    level: 2,
    rating: 4.9,
    portions: 4,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Нагрейте сливки с ванилью до 80°C. Взбейте желтки с сахаром до светлой массы.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Медленно влейте сливки в желтки, помешивая. Процедите через сито.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Разлейте по рамекинам, запекайте на водяной бане при 150°C 30 минут. Охладите 4 часа.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Перед подачей посыпьте сахаром, карамелизуйте горелкой.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Морковный торт с грецкими орехами — влажный и ароматный десерт',
      description:
        'Классический морковный торт с кремом из маскарпоне: пошаговый рецепт с фото. Секреты влажной текстуры, сочетание специй и идеальный баланс сладости. Выпекается 50 минут.',
      keywords: [
        'морковный торт',
        'десерт с морковью',
        'влажный торт',
        'ореховый десерт',
        'десерт с маскарпоне',
        'домашний торт',
        'десерт за 50 минут',
        'праздничный торт',
        'десерт со специями',
        'коричный десерт',
        'полезный десерт',
        'десерт с грецкими орехами',
        'торт без муки',
        'десерт к кофе',
        'американский торт',
      ],
      'og:title': 'Морковный торт с грецкими орехами — влажный и ароматный десерт',
      'og:description':
        'Классический морковный торт с кремом из маскарпоне: секреты влажной текстуры и сочетание специй.',
      'og:url': 'https://povreshka.ru/recipe/morkovnyy-tort-s-gretskimi-orekhami',
      'og:image': '/static/recipes/dessert/morkovnyy-tort-s-gretskimi-orekhami.jpeg',
      twitterTitle: 'Морковный торт с грецкими орехами — влажный и ароматный десерт',
      twitterDescription: 'Влажный морковный торт с грецкими орехами — неожиданно вкусно!',
      twitterImage: '/static/recipes/dessert/morkovnyy-tort-s-gretskimi-orekhami.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/morkovnyy-tort-s-gretskimi-orekhami',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/morkovnyy-tort-s-gretskimi-orekhami',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['морковный торт', 'десерт с морковью', 'влажный торт', 'ореховый десерт', 'десерт с маскарпоне'],
    categories: [{ name: 'dessert' }],
    key: 'morkovnyy-tort-s-gretskimi-orekhami',
    name: 'morkovnyy-tort-s-gretskimi-orekhami',
    img: '/static/recipes/dessert/morkovnyy-tort-s-gretskimi-orekhami.jpeg',
    title: 'Морковный торт с орехами',
    description:
      'Американская классика в изысканном исполнении — влажный пряный бисквит с тертой морковью и грецкими орехами, прослоенный воздушным кремом из маскарпоне с апельсиновой цедрой. Особенность рецепта — использование овсяной муки для нежной текстуры и сочетание пяти специй (корица, имбирь, мускат, гвоздика, кардамон).',
    calories: 410,
    preparation: 30,
    time: 80,
    level: 2,
    rating: 4.7,
    portions: 8,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Смешайте сухие ингредиенты. Отдельно взбейте яйца с сахаром, добавьте масло и морковь.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Соедините обе массы, добавьте орехи. Выпекайте при 180°C 50 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Для крема взбейте маскарпоне с сахарной пудрой и цедрой. Промажьте остывшие коржи.',
        ingredients: [],
      },
    ],
  },

  {
    metaSeo: {
      title: 'Пирожное Картошка — классический советский десерт за 20 минут',
      description:
        'Легендарное пирожное Картошка из детства: простой рецепт с печеньем и какао. Секреты идеальной формы, 3 варианта начинки и советы по украшению. Без выпечки, готовится за 20 минут + охлаждение.',
      keywords: [
        'пирожное картошка',
        'советский десерт',
        'десерт с печеньем',
        'десерт без выпечки',
        'шоколадное пирожное',
        'десерт за 20 минут',
        'десерт с какао',
        'домашние сладости',
        'ретро десерт',
        'десерт из детства',
        'быстрый десерт',
        'десерт с вареной сгущенкой',
        'праздничный десерт',
        'десерт к чаю',
        'постный вариант',
      ],
      'og:title': 'Пирожное Картошка — классический советский десерт за 20 минут',
      'og:description':
        'Легендарное пирожное Картошка из детства: простой рецепт с печеньем и какао. Без выпечки, готовится за 20 минут.',
      'og:url': 'https://povreshka.ru/recipe/pirozhnoye-kartoshka',
      'og:image': '/static/recipes/dessert/pirozhnoye-kartoshka.jpeg',
      twitterTitle: 'Пирожное Картошка — классический советский десерт за 20 минут',
      twitterDescription: 'Ностальгическое пирожное Картошка — вкус детства!',
      twitterImage: '/static/recipes/dessert/pirozhnoye-kartoshka.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/pirozhnoye-kartoshka',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/pirozhnoye-kartoshka',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'пирожное картошка',
      'советский десерт',
      'десерт с печеньем',
      'десерт без выпечки',
      'шоколадное пирожное',
    ],
    categories: [{ name: 'dessert' }],
    key: 'pirozhnoye-kartoshka',
    name: 'pirozhnoye-kartoshka',
    img: '/static/recipes/dessert/pirozhnoye-kartoshka.jpeg',
    title: 'Пирожное Картошка',
    description:
      'Культовый советский десерт, напоминающий картофельные клубни — готовится из крошки печенья со сгущенным молоком и какао. Особенность рецепта — сочетание ванильного печенья «Юбилейное» и топленого масла для аутентичного вкуса 80-х годов. Формируется вручную и обваливается в какао-порошке для характерного вида.',
    calories: 320,
    preparation: 20,
    time: 140,
    level: 1,
    rating: 4.9,
    portions: 10,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Измельчите печенье в крошку с помощью блендера или скалки. Добавьте какао и перемешайте.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте сгущенку с размягченным маслом до однородности. Соедините с печеньем.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Сформируйте шарики или клубни, обваляйте в какао. Охладите 2 часа.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Торт Медовик — классический рецепт с медовыми коржами',
      description:
        'Знаменитый Медовик с нежными коржами: пошаговый рецепт с фото. Секреты мягких коржей, идеального крема и правильной пропитки. Выпекается 40 минут + сборка.',
      keywords: [
        'медовик',
        'классический торт',
        'медовый торт',
        'десерт со сметанным кремом',
        'русский торт',
        'десерт за 40 минут',
        'торт с медом',
        'домашний торт',
        'праздничный десерт',
        'десерт к чаю',
        'воздушный торт',
        'десерт для гостей',
        'слоеный торт',
        'медовые коржи',
        'ретро десерт',
      ],
      'og:title': 'Торт Медовик — классический рецепт с медовыми коржами',
      'og:description': 'Знаменитый Медовик с нежными коржами: секреты мягких коржей и идеального крема.',
      'og:url': 'https://povreshka.ru/recipe/tort-medovik',
      'og:image': '/static/recipes/dessert/tort-medovik.jpeg',
      twitterTitle: 'Торт Медовик — классический рецепт с медовыми коржами',
      twitterDescription: 'Нежный Медовик с медовыми нотками — король русских тортов!',
      twitterImage: '/static/recipes/dessert/tort-medovik.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/tort-medovik',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/tort-medovik',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['медовик', 'классический торт', 'медовый торт', 'десерт со сметанным кремом', 'русский торт'],
    categories: [{ name: 'dessert' }],
    key: 'tort-medovik',
    name: 'tort-medovik',
    img: '/static/recipes/dessert/tort-medovik.jpeg',
    title: 'Торт Медовик',
    description:
      'Императорский десерт с 200-летней историей — нежные медовые коржи с ароматом корицы, прослоенные густой сметанной начинкой. Особенность рецепта — использование темного гречишного меда для коржей и томление готового торта 12 часов для идеальной пропитки.',
    calories: 380,
    preparation: 40,
    time: 520,
    level: 3,
    rating: 4.9,
    portions: 12,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'На водяной бане растопите мед с маслом и сахаром. Добавьте соду, размешивайте до появления пены.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Влейте яйца, затем постепенно добавляйте муку. Замесите мягкое тесто.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Разделите на 8 частей, раскатайте тонкие коржи. Выпекайте по 5-7 минут при 180°C.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Для крема взбейте сметану с сахарной пудрой. Соберите торт, посыпьте крошкой. Охладите 12 часов.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Безе — воздушное французское пирожное за 2 часа',
      description:
        'Идеальное безе с хрустящей корочкой: пошаговый рецепт с фото. Секреты устойчивых пиков, правильная температура сушки и варианты вкусов. Готовится 2 часа в духовке.',
      keywords: [
        'безе',
        'французское пирожное',
        'воздушный десерт',
        'десерт из белков',
        'меренга',
        'десерт за 2 часа',
        'хрустящий десерт',
        'легкий десерт',
        'десерт без муки',
        'десерт к чаю',
        'праздничный десерт',
        'домашнее безе',
        'десерт с сахаром',
        'ванильное безе',
        'цветное безе',
      ],
      'og:title': 'Безе — воздушное французское пирожное за 2 часа',
      'og:description': 'Идеальное безе с хрустящей корочкой: секреты устойчивых пиков и правильная температура сушки.',
      'og:url': 'https://povreshka.ru/recipe/beze',
      'og:image': '/static/recipes/dessert/beze.jpeg',
      twitterTitle: 'Безе — воздушное французское пирожное за 2 часа',
      twitterDescription: 'Воздушные безе с хрустящей корочкой — просто и изысканно!',
      twitterImage: '/static/recipes/dessert/beze.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/beze',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/beze',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['безе', 'французское пирожное', 'воздушный десерт', 'десерт из белков', 'меренга'],
    categories: [{ name: 'dessert' }],
    key: 'beze',
    name: 'beze',
    img: '/static/recipes/dessert/beze.jpeg',
    title: 'Безе классическое',
    description:
      'Французская меренга, запеченная до хрустящего состояния с нежной тающей серединой. Особенность рецепта — точное соотношение сахара и белков (2:1), добавление лимонного сока для стабилизации и медленная сушка при низкой температуре для идеальной текстуры без трещин.',
    calories: 120,
    preparation: 20,
    time: 140,
    level: 2,
    rating: 4.7,
    portions: 15,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'В чистой сухой миске взбейте белки с лимонным соком до мягких пиков.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Продолжая взбивать, добавляйте сахар по ложке. Добейтесь глянцевой плотной массы.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Отсадите безе кондитерским мешком на пергамент. Сушите в духовке при 100°C 2 часа.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Ленивый Наполеон — быстрый торт за 30 минут',
      description:
        'Гениальный рецепт ленивого Наполеона: хрустящие коржи и нежный заварной крем. Секреты быстрой сборки, 3 варианта коржей и советы по украшению. Готовится за 30 минут + пропитка.',
      keywords: [
        'ленивый наполеон',
        'быстрый торт',
        'десерт за 30 минут',
        'торт с заварным кремом',
        'домашний наполеон',
        'десерт из готовых коржей',
        'праздничный десерт',
        'легкий торт',
        'десерт для гостей',
        'слоеный десерт',
        'десерт к чаю',
        'хрустящий торт',
        'ванильный десерт',
        'ретро десерт',
        'постный вариант',
      ],
      'og:title': 'Ленивый Наполеон — быстрый торт за 30 минут',
      'og:description':
        'Гениальный рецепт ленивого Наполеона: хрустящие коржи и нежный заварной крем. Готовится за 30 минут.',
      'og:url': 'https://povreshka.ru/recipe/lenivyy-napoleon',
      'og:image': '/static/recipes/dessert/lenivyy-napoleon.jpeg',
      twitterTitle: 'Ленивый Наполеон — быстрый торт за 30 минут',
      twitterDescription: 'Ленивый Наполеон — вкус классики без хлопот!',
      twitterImage: '/static/recipes/dessert/lenivyy-napoleon.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/lenivyy-napoleon',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/lenivyy-napoleon',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'ленивый наполеон',
      'быстрый торт',
      'десерт за 30 минут',
      'торт с заварным кремом',
      'домашний наполеон',
    ],
    categories: [{ name: 'dessert' }],
    key: 'lenivyy-napoleon',
    name: 'lenivyy-napoleon',
    img: '/static/recipes/dessert/lenivyy-napoleon.jpeg',
    title: 'Ленивый Наполеон',
    description:
      'Гениальное упрощение классического торта — готовится из слоеного теста с заварным кремом за минимальное время. Особенность рецепта — использование готовых коржей или лаваша, быстрое приготовление крема на кукурузном крахмале и обязательная обсыпка крошкой для аутентичного вида.',
    calories: 350,
    preparation: 15,
    time: 195,
    level: 1,
    rating: 4.8,
    portions: 8,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Раскатайте слоеное тесто, нарежьте на квадраты. Выпекайте при 200°C 10 минут до золотистости.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Для крема смешайте молоко, яйца, сахар и крахмал. Варите до загустения, добавьте масло.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Соберите торт, чередуя коржи и крем. Обсыпьте крошкой, охладите 3 часа.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шу с кремом — воздушные профитроли за 1 час',
      description:
        'Французские профитроли Шу с заварным кремом: пошаговый рецепт с фото. Секреты пустот внутри, идеальный заварной крем и варианты начинок. Выпекается 25 минут.',
      keywords: [
        'шу с кремом',
        'французские профитроли',
        'воздушные пирожные',
        'десерт с заварным кремом',
        'десерт за 1 час',
        'легкие пирожные',
        'десерт из заварного теста',
        'праздничный десерт',
        'десерт для гостей',
        'кофейный десерт',
        'шоколадный шу',
        'ванильные профитроли',
        'десерт к чаю',
        'ресторанный десерт',
        'пошаговый рецепт',
      ],
      'og:title': 'Шу с кремом — воздушные профитроли за 1 час',
      'og:description': 'Французские профитроли Шу с заварным кремом: секреты пустот внутри и идеальный крем.',
      'og:url': 'https://povreshka.ru/recipe/shu-s-kremom',
      'og:image': '/static/recipes/dessert/shu-s-kremom.jpeg',
      twitterTitle: 'Шу с кремом — воздушные профитроли за 1 час',
      twitterDescription: 'Воздушные профитроли Шу с нежным кремом — французская классика!',
      twitterImage: '/static/recipes/dessert/shu-s-kremom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shu-s-kremom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shu-s-kremom',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'шу с кремом',
      'французские профитроли',
      'воздушные пирожные',
      'десерт с заварным кремом',
      'десерт за 1 час',
    ],
    categories: [{ name: 'dessert' }],
    key: 'shu-s-kremom',
    name: 'shu-s-kremom',
    img: '/static/recipes/dessert/shu-s-kremom.jpeg',
    title: 'Шу с кремом',
    description:
      "Классика французской кондитерской школы — воздушные полые пирожные из заварного теста, наполненные ванильным заварным кремом. Особенность рецепта — точное соблюдение пропорций теста (вода, мука, масло, яйца) и техника 'открытой духовки' для идеального подъема. Подаются присыпанными сахарной пудрой.",
    calories: 280,
    preparation: 35,
    time: 60,
    level: 3,
    rating: 4.9,
    portions: 12,
    used: [],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Для теста вскипятите воду с маслом и солью. Всыпьте муку, интенсивно размешивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: "Охладите до 60°C, добавляйте яйца по одному. Тесто должно стекать 'лентой'.",
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Отсадите шарики на пергамент. Выпекайте при 200°C 10 минут, затем при 180°C 15 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Для крема смешайте молоко, желтки, сахар и крахмал. Варите до загустения, добавьте ваниль.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Наполните остывшие профитроли кремом через отверстие снизу. Посыпьте пудрой.',
        ingredients: [],
      },
    ],
  },
]
