import { EQUIPMENTS } from '../equipments'
import { INGREDIENTS } from '../ingredients'

export const GRILL = [
  {
    metaSeo: {
      title: 'Шашлык из свинины на кефире',
      description:
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      keywords: ['шашлык', 'свинина', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
      'og:title': 'Шашлык из свинины на кефире',
      'og:description':
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      'og:image': '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
      twitterTitle: 'Шашлык из свинины на кефире',
      twitterDescription:
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'шашлык',
      'маринад для шашлыка',
      'рецепт шашлыка',
      'как приготовить шашлык',
      'шашлык из свинины',
      'маринад для шашлыка из свинины',
      'шашлык на мангале',
      'как мариновать шашлык',
      'как замариновать шашлык',
      'сочный шашлык',
      'вкусный шашлык',
      'лучший шашлык',
      'рецепт шашлыка из свинины',
      'шашлык из курицы',
      'маринад для шашлыка с уксусом',
      'маринад для шашлыка с луком',
      'маринад для шашлыка с кефиром',
      'маринад для шашлыка с минералкой',
      'шашлык в духовке',
      'шашлык на решетке',
      'шашлык на углях',
      'шашлык дома',
      'шашлык из баранины',
      'шашлык из говядины',
      'шашлык из индейки',
      'шашлык из рыбы',
      'овощной шашлык',
      'маринад для куриного шашлыка',
      'специи для шашлыка',
      'лук для шашлыка',
      'какой маринад для шашлыка',
      'как жарить шашлык на мангале',
      'сколько жарить шашлык',
      'чем поливать шашлык при жарке',
      'как понять что шашлык готов',
      'какое мясо лучше для шашлыка',
      'в каком маринаде лучше шашлык',
      'сколько шашлыка на человека',
      'сколько нужно мяса на шашлык',
      '1 кг шашлыка сколько порций',
      'цена шашлыка',
      'шашлык на майские праздники',
      'шашлык на выходные',
      'шашлык на даче',
      'шашлык на природе',
      'шашлык летом',
      'шашлык на Новый год',
      'домашний шашлык из свинины',
      'шашлык без мангала',
      'шашлык в банке',
      'шашлык в духовке в банке',
      'шашлык из курицы в духовке',
      'шашлык из свинины с луком',
    ],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-svininy-na-kefire',
    name: 'shashlyk-iz-svininy-na-kefire',
    img: '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
    title: 'Шашлык из свинины на кефире',
    description:
      'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
    calories: 1999.06,
    preparation: 240,
    time: 40,
    level: 1,
    rating: 5,
    portions: 4,
    used: [74.36, 179.36, 20.2],
    ingredients: [
      {
        ...INGREDIENTS.onion,
        count: 8,
      },
      {
        ...INGREDIENTS.salt,
        count: 5,
      },
      {
        ...INGREDIENTS.groundBlackPepper,
        count: 5,
      },
      {
        ...INGREDIENTS.dill,
        count: 0.5,
      },
      {
        ...INGREDIENTS.basil,
        count: 1,
      },
      {
        ...INGREDIENTS.parsley,
        count: 0.5,
      },
      {
        ...INGREDIENTS.porkNeck,
        count: 2,
      },
      {
        ...INGREDIENTS.kefir32,
        count: 600,
      },
      {
        ...INGREDIENTS.oliveOil,
        count: 4,
      },
    ],
    equipments: [
      EQUIPMENTS.bowl,
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.blender,
      EQUIPMENTS.spoon,
      EQUIPMENTS.grill,
      EQUIPMENTS.tongs,
      EQUIPMENTS.lid,
      EQUIPMENTS.paperTowel,
      EQUIPMENTS.skewers,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Подготовьте ингредиенты: хорошо промойте мясо и обсушите бумажным полотенцем. Удалите лишний жир и плёнки, чтобы шашлык получился мягким и не имел лишней жирности.',
        ingredients: [{ ...INGREDIENTS.porkNeck }],
      },
      {
        img: null,
        video: null,
        description:
          'Нарежьте свиную шею острым ножом на равные по размеру куски — так мясо прожарится равномерно и не пересохнет. Оптимально — кубики размером около 4–5 см.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Промойте зелень — укроп, базилик и петрушку — в холодной воде, затем обсушите. Разберите зелень руками и выложите в чашу блендера вместе с черешками.',
        ingredients: [{ ...INGREDIENTS.dill }, { ...INGREDIENTS.basil }, { ...INGREDIENTS.parsley }],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте к зелени оливковое или рафинированное растительное масло. Измельчите до состояния пасты — она придаст маринаду яркий аромат и насыщенный вкус.',
        ingredients: [{ ...INGREDIENTS.refinedVegetableOil }, { ...INGREDIENTS.oliveOil }],
      },
      {
        img: null,
        video: null,
        description:
          'В глубокой миске соедините куски мяса, кефир, луковые кольца, зелёную пасту, соль и перец. Всё хорошо перемешайте руками, чтобы маринад равномерно покрывал мясо.',
        ingredients: [
          { ...INGREDIENTS.kefir32 },
          { ...INGREDIENTS.onion },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Накройте миску крышкой или пищевой пленкой и оставьте мясо мариноваться минимум на 4 часа при комнатной температуре или на ночь в холодильнике.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Нанизайте мясо на шампуры или выложите на решетку. Жарьте на горячих углях до готовности, регулярно переворачивая, чтобы мясо подрумянилось со всех сторон. Подавайте с овощами и свежей зеленью.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из куриного бедра',
      description:
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      keywords: ['шашлык', 'курица', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
      'og:title': 'Шашлык из куриного бедра',
      'og:description':
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      'og:image': '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
      twitterTitle: 'Шашлык из куриного бедра',
      twitterDescription:
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['шашлык', 'курица', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-kurinogo-bedra',
    name: 'shashlyk-iz-kurinogo-bedra',
    img: '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
    title: 'Шашлык из куриного бедра',
    description:
      'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
    calories: 355,
    preparation: 120,
    time: 60,
    level: 1,
    rating: 5,
    portions: 8,
    used: [28.67, 14.61, 28.2],
    ingredients: [
      {
        ...INGREDIENTS.chickenThighFillet,
        count: 1,
      },
      {
        ...INGREDIENTS.carbonatedMineralWater,
        count: 100,
      },
      {
        ...INGREDIENTS.salt,
        count: 12,
      },
      {
        ...INGREDIENTS.groundBlackPepper,
        count: 2,
      },
      {
        ...INGREDIENTS.vegetableOil,
        count: 2,
      },
      {
        ...INGREDIENTS.onion,
        count: 1,
      },
      {
        ...INGREDIENTS.lavash,
        count: 2,
      },
      {
        ...INGREDIENTS.greens,
        count: 16,
      },
    ],
    equipments: [
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.bowl,
      EQUIPMENTS.spoon,
      EQUIPMENTS.lid,
      EQUIPMENTS.tongs,
      EQUIPMENTS.grill,
      EQUIPMENTS.skewers,
      EQUIPMENTS.paperTowel,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Филе куриного бедра тщательно промойте, обсушите бумажными полотенцами. Нарежьте мясо на крупные куски размером около 5–7 см. Посыпьте солью и молотым перцем, аккуратно перемешайте.',
        ingredients: [
          { ...INGREDIENTS.chickenThighFillet },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Очистите лук и нарежьте его полукольцами толщиной около 0.5–1 см. Добавьте его к мясу вместе с растительным маслом. Всё тщательно перемешайте ложкой или руками.',
        ingredients: [{ ...INGREDIENTS.onion }, { ...INGREDIENTS.vegetableOil }],
      },
      {
        img: null,
        video: null,
        description:
          'Влейте в мясо с луком газированную минеральную воду. Перемешайте всё ещё раз, накройте миску крышкой и оставьте мариноваться минимум на 2 часа.',
        ingredients: [{ ...INGREDIENTS.carbonatedMineralWater }],
      },
      {
        img: null,
        video: null,
        description:
          'Когда мясо замаринуется, удалите лишний лук. Нанизывайте курицу на шампуры или деревянные шпажки. Обжаривайте на гриле или сковороде-гриль до золотистой корочки со всех сторон.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Готовый шашлык подавайте с рубленой зеленью и свежим лавашом. Блюдо особенно вкусно в горячем виде прямо с огня.',
        ingredients: [{ ...INGREDIENTS.greens }, { ...INGREDIENTS.lavash }],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      description:
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      keywords: ['шашлык', 'курица', 'грудка', 'маринад', 'лимон', 'мед', 'чеснок', 'гриль'],
      'og:title': 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      'og:description':
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      'og:image': '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
      twitterTitle: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      twitterDescription:
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['шашлык', 'курица', 'грудка', 'маринад', 'лимон', 'мед', 'чеснок', 'гриль'],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-kurinyh-grudok',
    name: 'shashlyk-iz-kurinyh-grudok',
    img: '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
    title: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
    description:
      'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
    calories: 320,
    preparation: 180,
    time: 30,
    level: 1,
    rating: 5,
    portions: 6,
    used: [25.5, 15.2, 22.8],
    ingredients: [
      { ...INGREDIENTS.chickenBreastFillet, count: 1 },
      { ...INGREDIENTS.lemon, count: 1 },
      { ...INGREDIENTS.honey, count: 30 },
      { ...INGREDIENTS.garlic, count: 3 },
      { ...INGREDIENTS.oliveOil, count: 30 },
      { ...INGREDIENTS.salt, count: 10 },
      { ...INGREDIENTS.groundBlackPepper, count: 2 },
    ],
    equipments: [
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.bowl,
      EQUIPMENTS.spoon,
      EQUIPMENTS.lid,
      EQUIPMENTS.tongs,
      EQUIPMENTS.grill,
      EQUIPMENTS.skewers,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Куриную грудку нарежьте кубиками 4–5 см. Посолите, поперчите.',
        ingredients: [
          { ...INGREDIENTS.chickenBreastFillet },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте сок лимона, мёд, измельчённый чеснок и оливковое масло. Залейте маринадом курицу, перемешайте, накройте и оставьте на 3 часа.',
        ingredients: [
          { ...INGREDIENTS.lemon },
          { ...INGREDIENTS.honey },
          { ...INGREDIENTS.garlic },
          { ...INGREDIENTS.oliveOil },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Нанижите мясо на шпажки и жарьте на гриле 10–12 минут, переворачивая, до румяной корочки.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      description:
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным. Секреты правильного маринования и жарки.',
      keywords: [
        'шашлык из курицы',
        'куриный шашлык',
        'кефирный маринад',
        'маринад для шашлыка',
        'шашлык на кефире',
        'сочный шашлык',
        'рецепт шашлыка',
        'шашлык на мангале',
        'летний шашлык',
        'курица на гриле',
        'пряный шашлык',
        'шашлык с чесноком',
        'быстрый маринад',
        'шашлык для пикника',
        'восточный шашлык',
        'шашлык за 2 часа',
        'диетический шашлык',
        'шашлык без уксуса',
        'куриные бедра на гриле',
        'грудка на мангале',
        'шашлык с зеленью',
      ],
      'og:title': 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      'og:description':
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      'og:image': '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
      twitterTitle: 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      twitterDescription:
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из курицы', 'кефирный маринад', 'курица на мангале', 'сочный шашлык'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-kuritsy-v-kefirnom-marinade',
    name: 'shashlyk-iz-kuritsy-v-kefirnom-marinade',
    img: '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
    title: 'Шашлык из курицы в кефирном маринаде',
    description:
      'Невероятно сочный шашлык из курицы: кефирный маринад с чесноком и пряностями делает мясо мягким и ароматным. Идеальный вариант для пикника.',
    calories: 210,
    preparation: 20,
    time: 140,
    level: 2,
    rating: 4.8,
    portions: 4,
    used: [25, 12, 3],
    ingredients: [
      {
        name: 'Куриные бедра',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Кефир',
        gauge: 'мл',
        count: 250,
        img: null,
      },
      {
        name: 'Лук репчатый',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 4,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Паприка сладкая',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Кориандр молотый',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Зира',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Черный перец',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Свежая зелень (кинза/петрушка)',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал или гриль',
        img: null,
      },
      {
        name: 'Шампуры или решетка',
        img: null,
      },
      {
        name: 'Глубокая миска для маринования',
        img: null,
      },
      {
        name: 'Нож шеф-повара',
        img: null,
      },
      {
        name: 'Разделочная доска',
        img: null,
      },
      {
        name: 'Щипцы для гриля',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Подготовьте курицу: бедра промойте, обсушите и нарежьте на куски среднего размера (примерно 4-5 см). Удалите лишний жир и кожу при желании.',
        ingredients: [
          {
            name: 'Куриные бедра',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: в глубокой миске смешайте кефир, нарезанный кольцами лук, измельченный чеснок, оливковое масло и все специи. Тщательно перемешайте.',
        ingredients: [
          {
            name: 'Кефир',
            gauge: 'мл',
            count: 250,
            img: null,
          },
          {
            name: 'Лук репчатый',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 4,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Папика сладкая',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Кориандр молотый',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Зира',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Соль',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Черный перец',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте курицу в маринад, хорошо перемешайте, чтобы все кусочки были покрыты. Накройте пищевой пленкой и уберите в холодильник минимум на 2 часа (лучше на 4-6 часов).',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разожгите мангал. Когда угли покроются белым пеплом, нанижите курицу на шампуры, чередуя с луком из маринада. Жарьте 15-20 минут, регулярно переворачивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Подавайте горячим, посыпав свежей рубленой зеленью. Идеально сочетается с овощами-гриль и лавашом.',
        ingredients: [
          {
            name: 'Свежая зелень (кинза/петрушка)',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      description:
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов. Советы по приготовлению на углях.',
      keywords: [
        'шашлык из курицы',
        'соевый маринад',
        'имбирный маринад',
        'азиатский шашлык',
        'курица в соевом соусе',
        'шашлык с имбирем',
        'восточный шашлык',
        'быстрый маринад',
        'шашлык за 1 час',
        'куриные крылья на гриле',
        'шашлык с медом',
        'кисло-сладкий шашлык',
        'курица по-азиатски',
        'шашлык для пикника',
        'маринад с кунжутом',
        'диетический шашлык',
        'шашлык без уксуса',
        'куриная грудка на мангале',
        'острый шашлык',
        'шашлык с кунжутом',
        'восточные специи',
      ],
      'og:title': 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      'og:description':
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      'og:image': '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
      twitterTitle: 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      twitterDescription:
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из курицы', 'соевый маринад', 'курица с имбирем', 'азиатский шашлык'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-kuritsy-v-soevom-marinade',
    name: 'shashlyk-iz-kuritsy-v-soevom-marinade',
    img: '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
    title: 'Шашлык из курицы в соевом маринаде',
    description:
      'Азиатская версия шашлыка: соевый маринад с имбирем и медом придает курице насыщенный вкус с кисло-сладкими нотками. Быстрое маринование и аппетитная корочка.',
    calories: 230,
    preparation: 15,
    time: 75,
    level: 2,
    rating: 4.7,
    portions: 4,
    used: [27, 10, 5],
    ingredients: [
      {
        name: 'Куриная грудка',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Соевый соус',
        gauge: 'мл',
        count: 100,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Свежий имбирь',
        gauge: 'см',
        count: 5,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 3,
        img: null,
      },
      {
        name: 'Кунжутное масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Красный перец хлопьями',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Кунжут',
        gauge: 'ч.л',
        count: 2,
        img: null,
      },
      {
        name: 'Зеленый лук',
        gauge: 'шт',
        count: 3,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал или гриль',
        img: null,
      },
      {
        name: 'Шампуры или решетка',
        img: null,
      },
      {
        name: 'Пластиковый контейнер для маринования',
        img: null,
      },
      {
        name: 'Терка для имбиря',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Кулинарная кисть',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Куриную грудку промойте, обсушите и нарежьте на кубики примерно 4х4 см. Удалите все пленки и лишний жир.',
        ingredients: [
          {
            name: 'Куриная грудка',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: в миске смешайте соевый соус, мед, натертый имбирь, измельченный чеснок, кунжутное масло, лимонный сок и красный перец. Взбейте венчиком до однородности.',
        ingredients: [
          {
            name: 'Соевый соус',
            gauge: 'мл',
            count: 100,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Свежий имбирь',
            gauge: 'см',
            count: 5,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 3,
            img: null,
          },
          {
            name: 'Кунжутное масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Красный перец хлопьями',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Залейте курицу маринадом, перемешайте, чтобы все кусочки были покрыты. Оставьте мариноваться при комнатной температуре 30 минут, затем уберите в холодильник еще на 30 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разожгите мангал. Нанижите курицу на шампуры. Жарьте 10-12 минут, часто переворачивая и смазывая остатками маринада с помощью кисточки в последние 2 минуты.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Готовый шашлык посыпьте кунжутом и нарезанным зеленым луком. Подавайте сразу же, пока горячий.',
        ingredients: [
          {
            name: 'Кунжут',
            gauge: 'ч.л',
            count: 2,
            img: null,
          },
          {
            name: 'Зеленый лук',
            gauge: 'шт',
            count: 3,
            img: null,
          },
        ],
      },
    ],
  },
]
